// Spanish Instagram captions per post type and outcome.

import { COMPETITION_TYPES, TEAM_ID, TIMEZONE } from './config.js';

const fmtTime = new Intl.DateTimeFormat('es-EC', {
  hour: '2-digit', minute: '2-digit', hour12: false, timeZone: TIMEZONE,
});

// When ESPN marks the kickoff time as not confirmed (timeValid=false) the
// placeholder must not be converted to local time — format the day in UTC
// and show no time at all.
export function formatDayLine(dateIso, timeValid = true) {
  // "DOM 12 · JULIO" style for the poster.
  const d = new Date(dateIso);
  const parts = new Intl.DateTimeFormat('es-EC', {
    weekday: 'short', day: 'numeric', month: 'long',
    timeZone: timeValid ? TIMEZONE : 'UTC',
  }).formatToParts(d);
  const get = (t) => parts.find((p) => p.type === t)?.value || '';
  return `${get('weekday').replace('.', '')} ${get('day')} · ${get('month')}`.toUpperCase();
}

export function formatTimeLine(dateIso, timeValid = true) {
  if (!timeValid) return null;
  return fmtTime.format(new Date(dateIso));
}

function lduOutcome(match) {
  const ldu = match.lduIsHome ? match.home : match.away;
  const rival = match.lduIsHome ? match.away : match.home;
  if (ldu.winner) return 'win';
  if (rival.winner) return 'loss';
  return 'draw';
}

// ESPN disambiguates names like "Libertad (Ecuador)" — drop the parenthetical.
const cleanName = (s) => String(s).replace(/\s*\([^)]*\)\s*$/, '');

// Deterministic pick from a fixed set of short lines, keyed off the match id
// so re-generating the same post is byte-identical, but different matches
// don't all read the same way.
function pick(list, seed) {
  let h = 0;
  for (const c of String(seed)) h = (h * 31 + c.charCodeAt(0)) >>> 0;
  return list[h % list.length];
}

// The banks are short, original one-liners in the voice of the LDU hinchada
// (viejo amigo, Rey de Copas, Casa Blanca, Ponciano, Centrales, guambra),
// without copying full chants. Every line names the team — no generic
// motivational filler — and the closer is always a single clean line.
//
// Fixture announcements usually go out days before kickoff (the pipeline
// posts the "próximo partido" as soon as the previous match ends), so the
// default fixture bank is time-neutral. MATCHDAY_LINES ("hoy juega...") are
// only used when the caption is generated on the match day in Ecuador time.
const FIXTURE_LINES = [
  '¡Vamos, Liga!',
  'A alentar a la U como siempre.',
  'Con Liga a todas partes.',
  'Los Centrales ya viven la previa.',
  'Todos con la U.',
  'La hinchada alba ya está lista.',
  'Nada como ver jugar a Liga.',
  'Hincha de Liga desde guambra.',
  'Vamos con fe, vamos con Liga.',
  'La U no juega sola.',
  'A ganar, Liga.',
  'Con el Rey de Copas hasta el final.',
  '¡Liga, Liga, Liga!',
  'Todo Quito con la U.',
  'Somos la U.',
  'Liga es Liga.',
  '¡Dale, Liga!',
  'Se viene otro partido de la U.',
  'La previa alba ya arrancó.',
  'Ya huele a partido de Liga.',
  'Fe ciega en la U.',
  'Todo listo para alentar a la U.',
  'Otro capítulo del Rey de Copas.',
  'Vamos por los tres puntos, Liga.',
  'A Liga se la apoya siempre.',
  'El albo no camina solo.',
  'Quito ya está en modo Liga.',
  'Otra oportunidad para ver ganar a la U.',
  'Primero Liga, después todo lo demás.',
  'Se viene Liga, se viene la fiesta.',
  'A vivir otro partido con la U.',
  'Las ganas nunca faltan cuando juega Liga.',
  'Ya queremos ver a Liga en la cancha.',
  'Liga nos junta otra vez.',
  'Buen día para ser de Liga.',
  'El Rey de Copas no descansa.',
  'A empujar a la U desde donde estemos.',
  'La hinchada de Liga nunca falla.',
  'Un partido más con mi Liga querida.',
  'Vamos que se puede, Liga.',
  'Por la blanca, todo.',
  'Ya se siente el partido de la U.',
  'Que gane Liga, lo demás no importa.',
  'Aliento albo a full desde ya.',
  'La U mueve a todo Quito.',
  'De la previa al pitazo final, con la U.',
  'Vamos con todo, Liga.',
  'Este equipo merece todo el aliento albo.',
  'Otro día de fe alba.',
  'Con Liga hasta debajo del agua.',
  'Ya hay fecha para ver a la U.',
  'Se acerca otro partido de Liga.',
  'Cuenta regresiva para ver a Liga.',
  'Agenden nomás: juega la U.',
  'Atentos, que se viene la U.',
  'Nos vemos en la cancha, Liga.',
  'A prepararse, que viene partido de Liga.',
  'Liga vuelve a jugar y nosotros a alentar.',
  'Otro partido para seguir queriendo a la U.',
  'La blanca ya tiene rival.',
  'Que llegue pronto el partido de la U.',
  'Falta poco para ver a Liga.',
  'Todo Quito espera a la U.',
  'El próximo partido de Liga ya se siente.',
  'Ansiosos por ver a la U.',
  'Ya se palpita el partido de Liga.',
  'Guarden la fecha: juega Liga.',
  'Pronto vuelve a rodar la pelota para la U.',
  'Otro reto para el Rey de Copas.',
  'Semana de partido, semana de Liga.',
  'A esperar el pitazo con la blanca puesta.',
  'Ya queremos alentar a la U.',
  'La cita con Liga ya está agendada.',
  'Que venga ese partido, Liga.',
  'El hincha albo ya cuenta los días.',
  'Ya viene otro partido del Rey de Copas.',
  'Que llegue ya el día del partido de Liga.',
  'Un partido más al lado de la U.',
  'A preparar la garganta para alentar a Liga.',
  'Se acerca la próxima cita alba.',
  'Liga vuelve a la cancha y nosotros con ella.',
  'Ya casi juega la U.',
  'Nadie se pierde el partido de Liga.',
  'El viejo amigo ya prepara otra salida.',
  'Se viene el Rey de Copas.',
  'Partido nuevo, misma fe en Liga.',
  'Otra fecha para estar con la U.',
  'La camiseta alba ya está planchada.',
  'A contar las horas para ver a Liga.',
  'Liga no descansa y el hincha tampoco.',
  'Toca volver a alentar a la U.',
  'Ya asoma el próximo partido de Liga.',
  'Vuelve Liga, vuelve la alegría.',
  'Otro partido para gritar los goles de la U.',
  'Con la blanca puesta se espera mejor.',
  'Liga se viene con todo.',
  'Las ganas de ver a Liga no se aguantan.',
  'Se armó el plan: ver a la U.',
  'Liga en la cabeza toda la semana.',
  'De local o de visita, con Liga.',
  'Donde juegue la U, ahí estamos.',
  'No hay plan mejor que ver a Liga.',
  'La ilusión alba nunca descansa.',
  'A seguir a la U donde toque.',
  'El próximo rival ya sabe que Liga es Liga.',
  'Más fútbol para la gente de Liga.',
  'Que venga el rival que sea: somos la U.',
  'La familia alba ya se alista.',
  'El calendario marca lo importante: juega Liga.',
  'Todo gira alrededor de la U esta semana.',
  'Otra oportunidad para que brille la blanca.',
  'A guardar energías para alentar a Liga.',
  'El partido de la U ya está marcado en rojo.',
  'Ni un partido de Liga se deja pasar.',
  'Que la espera se haga corta, Liga.',
  'Se viene otra batalla para el Rey de Copas.',
  'Nada se siente como la previa de Liga.',
  'Los albos ya hacen planes para el partido.',
  'La U convoca y el hincha responde.',
  'Otro partido, otra cita con la blanca.',
  'Liga está por jugar y ya se nota el ambiente.',
  'El país ya sabe: pronto juega el Rey de Copas.',
  'A cargar pilas que juega la U.',
  'Vuelve a jugar la U, vuelve todo.',
  'Con Liga no hay partido chico.',
  'Cualquier cancha es buena si juega Liga.',
  'La blanca se alista para otra más.',
  'Como siempre, todos detrás de la U.',
];

const MATCHDAY_LINES = [
  'Hoy juega Liga.',
  'Hoy juega la U y Quito lo sabe.',
  'Día de Liga.',
  'La blanca sale a la cancha.',
  'Hoy Quito es de Liga.',
  'El Rey de Copas sale a la cancha.',
  'Hoy toca dejar todo por Liga.',
  'Que salga la U a ganar.',
  'Hoy se alienta a Liga hasta el final.',
  'Liga es el plan de hoy.',
  'Que ruede la pelota, que juegue Liga.',
  'El albo sale por los tres puntos.',
  'Un día perfecto para ver a Liga.',
  'Ya es hora de ver a Liga.',
  'Liga juega y todo lo demás espera.',
  'Hoy se defiende la blanca.',
  'Otro día para gritar por Liga.',
  'Quito despierta pensando en Liga.',
  'La camiseta blanca sale a hablar en la cancha.',
  'Que empiece la fiesta alba.',
  'Hoy más que nunca, todos con Liga.',
  'Hoy toca ganar, Liga.',
  'El viejo amigo sale a la cancha.',
  'Nervios de siempre: juega Liga.',
  'Hoy hay Liga.',
  'A la cancha, albos.',
  'Hoy se suda la camiseta de Liga.',
  'El plan de hoy: Liga y nada más.',
  'Con la U desde el calentamiento.',
  'Con la blanca puesta desde temprano.',
  'Hoy juega el Rey de Copas.',
  'Liga en la cancha, nosotros en el aliento.',
  'Que sea un gran día para Liga.',
  'La U es la U, y hoy juega.',
  'La cita de hoy es con Liga.',
  'Se paraliza todo: juega la U.',
  'Hoy defendemos la blanca todos juntos.',
  'Hay Liga y eso alegra el día.',
  'Hoy se grita por la U.',
  'Siempre es buen día si juega la U.',
  'Hoy jugamos todos con Liga.',
  'Ni frío ni lluvia: hoy juega Liga.',
  'Liga de mis amores, hoy nos vemos.',
  'La blanca manda hoy.',
  'Hoy hay que estar con Liga.',
  'El país sabe: hoy juega el Rey de Copas.',
  'Hoy late fuerte el corazón albo.',
  'Ya es día de ponerse la camiseta de Liga.',
  'La banda alba ya calienta la garganta.',
  'Albos hoy y siempre.',
  'Llegó el día: juega Liga.',
  'Por fin juega la U.',
  'Es hoy, es hoy: juega Liga.',
  'Hoy nos vemos, Liga.',
  'Hoy manda Liga.',
  'Hoy no se planea nada: juega Liga.',
  'Hoy la agenda tiene un solo punto: Liga.',
  'Hoy sale la U y todo se acomoda.',
  'Hoy hay cita con el Rey de Copas.',
  'Hoy se canta por Liga.',
  'Ya es hoy: juega la U.',
  'El día llegó: la U a la cancha.',
  'Hoy los nervios son albos.',
  'Hoy toca empujar a la U los 90 minutos.',
  'Hoy ni el almuerzo importa: juega Liga.',
  'Hoy se defiende la camiseta de Liga.',
  'Hoy juega la blanca.',
  'Hoy, como siempre, con la U.',
  'Hoy Liga sale a ganar.',
  'Las horas pasan lento cuando juega Liga.',
  'Hoy se alienta a la U desde donde sea.',
  'Hoy vuelve a jugar el viejo amigo.',
  'Todo listo: hoy juega el Rey de Copas.',
  'Hoy la garganta se gasta por Liga.',
  'Hoy no se falla: todos con la U.',
  'Hoy se siente distinto: juega Liga.',
  'Hoy la blanca, siempre la blanca.',
  'Que arranque de una vez el partido de Liga.',
  'Hoy juega mi Liga querida.',
  'Hoy hay razón para sonreír: juega la U.',
  'Hoy el plan es albo.',
  'Hoy Quito habla de Liga.',
  'Hoy más albos que nunca.',
  'Faltan horas para ver a la U.',
  'Hoy toca vivir otro partido de Liga.',
  'Ya mismo juega Liga.',
  'Hoy se cumple el ritual albo.',
  'Hoy apoyamos a Liga de principio a fin.',
];

const WIN_LINES = [
  'Tres puntos más para la U.',
  'Ganar con Liga no se compara con nada.',
  'Triunfo albo.',
  'El Rey de Copas hizo lo suyo.',
  'Qué lindo verte ganar, Liga.',
  'Fiesta alba.',
  'Fiesta en Ponciano.',
  'Sonríe la Casa Blanca.',
  'Ganó la U y Quito sonríe.',
  'Qué bien se duerme cuando gana Liga.',
  'La blanca se hizo respetar.',
  'Así se juega con la camiseta de Liga.',
  'Victoria alba.',
  'Otro triunfo del viejo amigo.',
  'Liga es Liga.',
  'Que siga la racha, Liga.',
  'Grande, Liga.',
  'Bien, Liga, bien.',
  'Puro orgullo albo.',
  '¡Vamos, Liga!',
  'Los tres puntos son de la U.',
  'Hoy se festeja con la blanca puesta.',
  'Ganó mi Liga querida.',
  'Tremendo triunfo de la U.',
  'El albo está de fiesta.',
  '¡Liga, Liga, Liga!',
  'Ganó Liga y punto.',
  'De la mano de Liga vamos por más.',
  'Esto es Liga.',
  'Ganó Liga y el día se arregla solo.',
  'La U lo volvió a hacer.',
  'Ganó la U, alegría pura.',
  'Tres puntos bien albos.',
  'La blanca ganó como se debe.',
  'Hoy Quito es más albo que nunca.',
  'Se ganó con la garra de Liga.',
  'Liga dejó todo en la cancha y se llevó los tres puntos.',
  'El viejo amigo nos dio otra alegría.',
  'Ganó el Rey de Copas, como debe ser.',
  'Qué orgullo esta Liga.',
  'Ganar así, con la blanca, no tiene precio.',
  'Otra alegría gracias a Liga.',
  'La U nos regaló otra sonrisa.',
  'Se festeja en toda casa alba.',
  'Triunfazo de la U.',
  'Qué manera de ganar, Liga.',
  'Esta Liga da gusto.',
  'La blanca brilló hoy.',
  'Victoria con sabor a Liga.',
  'Ganamos todos cuando gana la U.',
  'El albo cumplió.',
  'Hoy se canta más fuerte por Liga.',
  'La Casa Blanca está de fiesta.',
  'Celebra Ponciano.',
  'Aplausos para la U.',
  'Sonrisa alba para toda la semana.',
  'Ganó Liga: mejor plan no hay.',
  'La U mandó en la cancha.',
  'Tres puntitos más para Liga.',
  'El Rey de Copas sigue sumando.',
  'Liga, siempre Liga.',
  'Hoy sí, Liga querida.',
  'Ganó la U y no se habla de otra cosa.',
  'Un gusto verte así, Liga.',
  'Cada vez más hincha de Liga.',
  'Se respeta a la U.',
  'Enorme triunfo albo.',
  'La U sabe ganar.',
  'Y la U va por más.',
  'Este triunfo es de todo el pueblo albo.',
  'Así me gusta, Liga.',
  'La blanca no se mancha.',
  'Otra vez festejando con Liga.',
  'Nada mejor que un triunfo de la U.',
  'Liga responde en la cancha.',
  'Vamos así, Liga.',
  'Ganó la U querida.',
  'Grande la U.',
  'Enorme, Liga.',
  'Qué golazo de día: ganó Liga.',
  'Hoy ganó la garra alba.',
  'Alegría alba de punta a punta.',
  'Que se repita, Liga.',
  'Triunfo para la gente de Liga.',
  'La U festeja y nosotros con ella.',
  'Otro triunfo para la historia alba.',
  'Se ganó a lo Liga.',
  'Ganó Liga y se nota en la calle.',
  'Un triunfo más para el Rey de Copas.',
  'Ganó Liga, como tiene que ser.',
  'Los albos festejan hoy.',
  'La camiseta alba respondió.',
  'Sube el ánimo: ganó la U.',
  'Liga nos tiene acostumbrados a esto.',
  'Se cantó fuerte y ganó Liga.',
  '¡Qué triunfo, Liga!',
  'Ganó la U y se festeja como debe ser.',
  'La alegría es alba.',
  'Otra vez ganó Liga, qué costumbre más linda.',
  'Ganó Liga y todo pinta mejor.',
  'Sonríen los albos.',
  'Ganó la U y el día está completo.',
  'Otra alegría firmada por Liga.',
  'El Rey de Copas manda.',
  'Tres puntos con sello albo.',
  'Cómo no quererte, Liga.',
  'Ganó Liga y lo demás puede esperar.',
  'Puro festejo albo.',
  'Aplausos de pie para Liga.',
  'La U cumplió y de qué manera.',
  'Se ganó y se disfruta, Liga.',
  'Liga ganadora, hinchada feliz.',
  'Que ganar se haga costumbre, Liga.',
  'La sonrisa de hoy la puso Liga.',
  'Triunfo albo de los buenos.',
  'Liga hizo su trabajo: ganar.',
  'Con triunfo de Liga, todo está bien.',
  'Ganó Liga, festeja Quito.',
  'El festejo albo no se guarda.',
  'Bien jugado y bien ganado, Liga.',
  'Otro triunfo albo para la colección.',
  'Feliz el que es de Liga.',
  'Tres puntos y gracias, Liga.',
  'Se llevó todo la U.',
  'La blanca festeja y con razón.',
  'Ganó Liga y eso siempre alegra.',
  'De estas victorias vive el hincha albo.',
  'Qué felicidad ser de Liga.',
  'Ganó la U, canta la hinchada.',
  'Que siga la fiesta alba.',
  'Ganó Liga: no hay mejor noticia.',
  'Festeja cada rincón albo del país.',
  'Suma de a tres la U.',
  'Liga lo hizo de nuevo.',
  'Victoria y a seguir, Liga.',
  'Hoy es un buen día: ganó Liga.',
  'Nada supera ver ganar a la U.',
];

const DRAW_LINES = [
  'Sabor a poco para la U.',
  'Un punto y a seguir, Liga.',
  'La U merecía más.',
  'Da iras, pero con Liga hasta el final.',
  'Empate que le queda corto a Liga.',
  'Liga dejó dos puntos en el camino.',
  'A la U le faltó el gol.',
  'A Liga se la alienta igual.',
  'La próxima gana la U.',
  'El aliento albo no se negocia.',
  'Liga tiene con qué dar más.',
  'Un punto más para Liga.',
  'La U sigue en la pelea.',
  'Faltó el gol, no el aliento albo.',
  'Toca mejorar, Liga.',
  'La fe alba sigue intacta.',
  'Se sigue sumando con la U.',
  'Empató Liga y quedó debiendo.',
  'El Rey de Copas quedó en deuda.',
  'A pensar en el próximo, Liga.',
  'Igual seguimos con la U.',
  'Liga merece más y lo sabe.',
  'Siempre con Liga, hasta en los empates.',
  'Quedó debiendo la blanca.',
  'Empate que deja deberes a Liga.',
  'La U dio para más.',
  'Ni modo: seguimos con Liga.',
  'Punto albo y ganas de más.',
  'A Liga le faltó puntería.',
  'La blanca merecía los tres puntos.',
  'No alcanzó, Liga.',
  'Un punto para la U y a lo que sigue.',
  'El empate no cambia el amor por Liga.',
  'Esta Liga da para más.',
  'A seguir trabajando, Liga.',
  'Punto que suma para la U.',
  'La próxima es de Liga.',
  'Faltó el último toque, Liga.',
  'Ganas de que ya juegue de nuevo la U.',
  'Con la U igual hasta el final.',
  'Empate y a pensar en lo que viene, Liga.',
  'El hincha albo no se conforma.',
  'Se rescató un punto, Liga.',
  'No era el día de la U.',
  'Se sumó de a uno con Liga.',
  'A mejorar rapidito, Liga.',
  'Liga puede más y lo va a demostrar.',
  'La fe alba no se mueve por un empate.',
  'Tranquilos: Liga siempre responde.',
  'Un empate no borra lo que es Liga.',
  'Quedan cosas por pulir, Liga.',
  'Igualdad y a seguir con la U.',
  'Al hincha de Liga le quedó gusto a poco.',
  'Otro día será, Liga.',
  'El aliento por la U no baja.',
  'No se ganó, pero con Liga siempre.',
  'La blanca dejó dudas hoy.',
  'Punto trabajado de la U.',
  'Se esperaba más de Liga hoy.',
  'Ya vendrá la victoria, Liga.',
  'Paciencia alba: esto sigue.',
  'Que la próxima sea con triunfo, Liga.',
  'Suma corta para la U.',
  'A darle la vuelta a esto, Liga.',
  'Sin triunfo, pero nunca sin Liga.',
  'Empate en la cancha; en el aliento ganó Liga.',
  'A la próxima con todo, Liga.',
  'El gol se le negó a la U.',
  'Liga empató; el hincha sigue firme.',
  'Un puntito para Liga.',
  'La U no se conforma; nosotros tampoco.',
  'Falta poco para que a Liga le salga todo.',
  'Liga va a estar bien; siempre está.',
  'Cabeza arriba, Liga.',
  'A Liga se le pide más porque puede más.',
  'La fe en la U sigue entera.',
  'Todo el aliento a Liga, siempre.',
  'Se viene más de Liga, seguro.',
  'A cerrar mejor los partidos, Liga.',
  'De estos empates Liga aprende.',
  'Quedó picando el triunfo, Liga.',
  'El punto no alcanza para la U.',
  'Faltó poquito, Liga.',
  'Ni modo, así es el fútbol; con Liga siempre.',
  'Las ganas de ver ganar a la U siguen intactas.',
  'Empató la U; se sigue.',
  'No se pudo ganar, Liga.',
  'Punto que sabe a poquito, Liga.',
  'La blanca quería más.',
  'A la U se le escapó el triunfo.',
  'Un puntito y a lo que viene, Liga.',
  'Con Liga se sigue, empate o no.',
  'La hinchada alba quería los tres puntos.',
  'Que el próximo sea triunfo albo.',
  'El aliento a la U no se toca.',
  'Se sumó uno; Liga quiere tres.',
  'A la U le tocó repartir puntos.',
  'Liga queda debiendo y el hincha esperando.',
  'Se esperaba el triunfo de la U.',
  'Ya vendrán los tres puntos, Liga.',
  'Ni triunfo ni derrota; Liga sigue.',
  'Igual se alentó con todo a la U.',
  'Nos quedamos con ganas de más, Liga.',
  'Que no se repita, Liga: a ganar la próxima.',
  'El hincha de Liga quiere victorias.',
  'Falta afinar detalles, Liga.',
  'A la U le faltó cerrar el partido.',
  'Uno más para Liga; pudieron ser tres.',
  'Tampoco se perdió; vamos, Liga.',
  'Sigue invicta la fe en la U.',
  'La blanca no pasó del empate.',
  'A seguir creyendo en la U.',
  'Habrá revancha en la próxima, Liga.',
];

const LOSS_LINES = [
  'Duele porque es Liga.',
  'Ahora más que nunca, Liga.',
  'Con la U en las buenas y en las malas.',
  'Da iras ver perder a Liga.',
  'A Liga no se la deja sola.',
  'De Liga no se baja nadie.',
  'La U se levanta, siempre lo ha hecho.',
  'El albo sabe levantarse.',
  'Toca responder, Liga.',
  'La camiseta de Liga exige más.',
  'La U va a volver, siempre vuelve.',
  'Con más razón, todos con Liga.',
  'Esto se arregla ganando, Liga.',
  'El hincha albo siempre está.',
  'Ni perdiendo se deja de ser de Liga.',
  'Arriba esa cabeza, Liga.',
  'Seguimos con la U, como siempre.',
  'Mal partido, mismo sentimiento albo.',
  'El Rey de Copas no se rinde.',
  'Liga es más grande que una derrota.',
  'La hinchada alba no abandona.',
  'Vamos, Liga, que esto sigue.',
  'En las malas se ve al hincha de Liga.',
  'Hoy tocó sufrir con Liga.',
  'Hoy no se pudo, Liga.',
  'Mañana se vuelve a creer en la U.',
  'A Liga se la quiere igual.',
  'El amor por Liga no depende del resultado.',
  'Golpe duro, pero somos de Liga.',
  'Nadie deja de ser albo por una derrota.',
  'Se perdió; se sigue con la U.',
  'Cabeza fría y a trabajar, Liga.',
  'Duele ver así a la U.',
  'Toca levantarse, Liga.',
  'Esta derrota también se carga con la blanca puesta.',
  'Los hinchas de Liga no se esconden.',
  'Días malos también hay; Liga sigue.',
  'Que nadie dude de la U.',
  'La U sabe salir de estas.',
  'Se pierde un partido, no la fe alba.',
  'A la U se la banca en las malas.',
  'Derrota amarga, aliento albo intacto.',
  'El que es de Liga, es de Liga siempre.',
  'Tranquilos, que Liga vuelve.',
  'Perdió Liga y duele de verdad.',
  'A recuperarse pronto, Liga.',
  'La blanca exige levantarse ya.',
  'Hoy tocó perder; el albo sigue firme.',
  'Ni así se suelta a la U.',
  'Más unidos que nunca con Liga.',
  'Al mal tiempo, más aliento para Liga.',
  'Se aprende y se sigue, Liga.',
  'Duele hoy, se corrige mañana, Liga.',
  'El Rey de Copas va a responder.',
  'La historia de Liga pesa más que esto.',
  'Nos dolió a todos los albos.',
  'Que la próxima sea revancha, Liga.',
  'Momento de estar más cerca de la U.',
  'Ninguna derrota borra al Rey de Copas.',
  'Se cae, se levanta: así es Liga.',
  'En las buenas cualquiera; en las malas, los de Liga.',
  'Hoy en silencio, mañana alentando a Liga.',
  'Va a doler hasta que juegue de nuevo la U.',
  'Confianza en Liga, hoy más que nunca.',
  'Sin excusas, Liga: a mejorar.',
  'Perder también es parte; abandonar a Liga, jamás.',
  'El aguante albo no se discute.',
  'Nada cambia: Liga es Liga.',
  'Hoy perdimos con la U; mañana ganamos con ella.',
  'Que este golpe despierte a Liga.',
  'La derrota duele; ser de Liga, jamás.',
  'Todos tranquilos: la U siempre regresa.',
  'Se sufre porque se quiere a Liga.',
  'A cerrar filas con la U.',
  'El aliento a Liga sube en las malas.',
  'Ser albo también es esto.',
  'Liga tiene con qué levantarse.',
  'Ya habrá revancha para la U.',
  'Ni un día malo apaga a Liga.',
  'De las derrotas también se sale, Liga.',
  'Dolió, pero acá seguimos con Liga.',
  'Perder no cambia nada: Liga siempre.',
  'El cariño por la U no se toca.',
  'Un tropiezo no borra a la U.',
  'Tocó la mala; seguimos con Liga.',
  'Se perdió el partido, no el amor por la U.',
  'La derrota pasa; Liga queda.',
  'Ni las derrotas espantan al hincha albo.',
  'Se pierde y se aguanta; somos de Liga.',
  'A la U la levantamos entre todos.',
  'De estas caídas Liga sabe volver.',
  'El escudo de Liga pesa más que un mal día.',
  'A pensar en lo que viene, Liga.',
  'Perdió Liga; toca aguantar y volver.',
  'Ninguna derrota es más fuerte que la U.',
  'Duele el resultado, no ser de la U.',
  'A dar vuelta la página, Liga.',
  'Otro día se ganará con la U.',
  'Se apoya más fuerte cuando pierde Liga.',
  'El aguante por la U se demuestra ahora.',
  'Nos toca empujar más que nunca a la U.',
  'Ya vendrá la alegría de nuevo con Liga.',
  'Ni hoy ni nunca se abandona a la U.',
  'Con la camiseta de Liga se pierde de pie.',
  'Malos partidos hay; malos hinchas de Liga, no.',
  'Ánimo, Liga, que la hinchada empuja.',
  'El Rey de Copas tiene historia para levantarse.',
  'Fuerza, Liga.',
  'Un mal marcador no cambia la historia alba.',
  'A la próxima se sale con todo, Liga.',
];

const STANDINGS_LINES = [
  'Partido a partido con la U.',
  'La tabla habla, Liga decide en la cancha.',
  'A seguir sumando, Liga.',
  'Paso a paso con la U.',
  'El objetivo de Liga está claro.',
  'La U sigue en carrera.',
  'Se pelea hasta el final con Liga.',
  'Cada punto albo cuesta y vale.',
  'Vamos por más, Liga.',
  'El Rey de Copas quiere más.',
  'Liga quiere estar arriba, como siempre.',
  'Fecha a fecha con Liga.',
  'Los puntos de Liga se sudaron todos.',
  'Queda campeonato y queda Liga.',
  'Con la U hasta la última fecha.',
  'El Rey de Copas no se guarda nada.',
  'A seguir escalando, Liga.',
  'Todo se define en la cancha, Liga.',
  'La U va fecha a fecha.',
  'Los números pasan; Liga queda.',
  'Aliento albo en cada fecha.',
  'Se suma y se sueña con Liga.',
  'El objetivo albo sigue en pie.',
  'Liga compite siempre.',
  'Punto a punto con la U.',
  'Nadie regala nada; Liga tampoco.',
  'Sigue la pelea y sigue Liga.',
  'Lo de Liga se construye cada fecha.',
  'Hasta el final con el Rey de Copas.',
  'La U nunca deja de pelear.',
  'Se viene lo mejor de Liga.',
  'La tabla se pelea con garra alba.',
  'Así marcha la U.',
  'La tabla es solo una foto; Liga es la película.',
  'Cada fecha cuenta para Liga.',
  'La U suma y sigue.',
  'Liga pelea, como siempre.',
  'De la tabla se habla; por Liga se alienta.',
  'El campeonato es largo y Liga está.',
  'A la U se la sigue toda la temporada.',
  'La tabla es del momento; Liga es de siempre.',
  'Esté donde esté, es la U.',
  'La meta alba sigue firme.',
  'Quedan fechas y quedan ganas, Liga.',
  'El hincha albo revisa la tabla y sigue creyendo.',
  'Se sueña en grande con el Rey de Copas.',
  'Cada fecha es una nueva chance para Liga.',
  'La tabla se mueve; el aliento a Liga no.',
  'La blanca sigue en la pelea del torneo.',
  'Falta campeonato y sobra fe en Liga.',
];

// Safety net: every closer must name the team explicitly.
function buildCloserBank(lines) {
  const identity = /\b(Liga|alb[ao]s?|Casa Blanca|Ponciano|camiseta|viejo amigo|La U|Centrales|Rey de Copas|blanca)\b/i;
  return lines.filter((line) => identity.test(line));
}

const FIXTURE_CLOSERS = buildCloserBank(FIXTURE_LINES);
const MATCHDAY_CLOSERS = buildCloserBank(MATCHDAY_LINES);
const RESULT_CLOSERS = {
  win: buildCloserBank(WIN_LINES),
  draw: buildCloserBank(DRAW_LINES),
  loss: buildCloserBank(LOSS_LINES),
};
const STANDINGS_CLOSERS = buildCloserBank(STANDINGS_LINES);

export const captionClosersForTest = {
  fixture: FIXTURE_CLOSERS,
  matchday: MATCHDAY_CLOSERS,
  win: RESULT_CLOSERS.win,
  draw: RESULT_CLOSERS.draw,
  loss: RESULT_CLOSERS.loss,
  standings: STANDINGS_CLOSERS,
};

// Calendar day in Ecuador, for deciding "hoy juega" vs anticipation lines.
const fmtDayKey = new Intl.DateTimeFormat('en-CA', {
  year: 'numeric', month: '2-digit', day: '2-digit', timeZone: TIMEZONE,
});

export function buildCaption(postType, match, extras = null, now = new Date()) {
  const comp = COMPETITION_TYPES[match.competitionType] || COMPETITION_TYPES.otra;
  const rival = match.home.id === TEAM_ID ? match.away : match.home;
  const verb = match.lduIsHome ? 'recibe a' : 'visita a';
  const score = `${cleanName(match.home.shortName)} ${match.home.score ?? '-'} - ${match.away.score ?? '-'} ${cleanName(match.away.shortName)}`;

  if (postType === 'fixture') {
    const timeValid = match.timeValid !== false;
    const day = new Intl.DateTimeFormat('es-EC', {
      weekday: 'long', day: 'numeric', month: 'long',
      timeZone: timeValid ? TIMEZONE : 'UTC',
    }).format(new Date(match.date));
    const time = timeValid ? `${fmtTime.format(new Date(match.date))} (Ecuador)` : 'Hora por confirmar';
    const venue = match.venue ? `\n🏟️ ${match.venue}${match.city ? `, ${match.city}` : ''}` : '';
    // "Hoy juega..." only when posting on the match day itself; unconfirmed
    // kickoff times can't be trusted for a same-day claim.
    const isMatchday = timeValid && fmtDayKey.format(now) === fmtDayKey.format(new Date(match.date));
    const closer = pick(isMatchday ? MATCHDAY_CLOSERS : FIXTURE_CLOSERS, match.id);
    return (
      `⚪️🔴 LDU ${verb} ${cleanName(rival.name)} · ${comp.label}` +
      `\n📅 ${day.charAt(0).toUpperCase() + day.slice(1)}` +
      `\n⏰ ${time}` +
      venue +
      `\n\n${closer}\n\n${comp.hashtags}`
    );
  }

  const outcome = lduOutcome(match);
  const opener = {
    win: '⚪️🔴 ¡Ganó Liga!',
    draw: '⚪️🔴 Empate.',
    loss: '⚪️🔴 Liga cayó.',
  }[outcome];
  const venue = match.venue ? `\n🏟️ ${match.venue}` : '';
  // Cup ties decided from the spot: the 90' score alone would read wrong.
  const pens = match.penalties
    ? `\n🎯 Penales: ${match.penalties.home} - ${match.penalties.away}`
    : '';
  // LDU goalscorers (from the ESPN match summary), when available.
  const lduScorers = (match.lduIsHome ? extras?.scorers?.home : extras?.scorers?.away) || [];
  const goals = lduScorers.length
    ? `\n⚽️ ${lduScorers
        .map((s) => `${s.name}${s.og ? ' (AG)' : s.pen ? ' (P)' : ''} ${s.minutes.join(' ')}`)
        .join(' · ')}`
    : '';
  const closer = pick(RESULT_CLOSERS[outcome], match.id);
  return (
    `${opener} ${score}\n${comp.label}` +
    pens +
    goals +
    venue +
    `\n\n${closer}\n\n${comp.hashtags}`
  );
}

// Caption for the "tabla de posiciones" post. Deterministic per table state,
// so re-generating the same table is byte-identical.
export function buildStandingsCaption(standings, teamId = TEAM_ID) {
  const ldu = standings.entries.find((e) => e.team.id === teamId);
  const round = ldu?.played ?? Math.max(...standings.entries.map((e) => e.played));
  const leader = standings.entries[0];
  const lines = [`⚪️🔴 Así está la tabla de la LigaPro tras la fecha ${round}.`];
  if (ldu) {
    lines.push(`📊 LDU: ${ldu.rank}.º con ${ldu.points} puntos (${ldu.played} PJ, ${ldu.goalDiff} DG).`);
    if (ldu.rank !== 1 && leader) {
      lines.push(`🔝 Líder: ${cleanName(leader.team.shortName)} con ${leader.points} puntos.`);
    }
  }
  const closer = pick(STANDINGS_CLOSERS, `tabla-${round}-${ldu?.rank ?? ''}-${ldu?.points ?? ''}`);
  return (
    lines.join('\n') +
    `\n\n${closer}\n\n#LDU #LigaDeQuito #LigaPro #SerieA #TablaDePosiciones #FutbolEcuatoriano`
  );
}
